import time

from PyQt5 import *
import os
import sys
from PyQt5.QtWidgets import *
from messagesBox import msgBox
from ExportFile import DataBase


class Ui_export(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 536)
        MainWindow.setMinimumSize(QtCore.QSize(915, 536))
        MainWindow.setMaximumSize(QtCore.QSize(915, 536))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 861, 401))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(12, 32, 95, 24))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_pat = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pat.setGeometry(QtCore.QRect(13, 101, 194, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_pat.setFont(font)
        self.checkBox_pat.setObjectName("checkBox_pat")
        self.checkBox_ins = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_ins.setGeometry(QtCore.QRect(13, 64, 275, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ins.setFont(font)
        self.checkBox_ins.setObjectName("checkBox_ins")
        self.checkBox_oop = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_oop.setGeometry(QtCore.QRect(13, 249, 247, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_oop.setFont(font)
        self.checkBox_oop.setObjectName("checkBox_oop")
        self.checkBox_ipd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_ipd.setGeometry(QtCore.QRect(13, 286, 175, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_ipd.setFont(font)
        self.checkBox_ipd.setObjectName("checkBox_ipd")
        self.checkBox_irf = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_irf.setGeometry(QtCore.QRect(13, 323, 237, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_irf.setFont(font)
        self.checkBox_irf.setObjectName("checkBox_irf")
        self.checkBox_opd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_opd.setGeometry(QtCore.QRect(13, 138, 300, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_opd.setFont(font)
        self.checkBox_opd.setObjectName("checkBox_opd")
        self.checkBox_orf = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_orf.setGeometry(QtCore.QRect(13, 175, 257, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_orf.setFont(font)
        self.checkBox_orf.setObjectName("checkBox_orf")
        self.checkBox_odx = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_odx.setGeometry(QtCore.QRect(13, 212, 260, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_odx.setFont(font)
        self.checkBox_odx.setObjectName("checkBox_odx")
        self.checkBox_cht = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_cht.setGeometry(QtCore.QRect(413, 138, 237, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cht.setFont(font)
        self.checkBox_cht.setObjectName("checkBox_cht")
        self.checkBox_cha = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_cha.setGeometry(QtCore.QRect(413, 175, 288, 29))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cha.setFont(font)
        self.checkBox_cha.setObjectName("checkBox_cha")
        self.checkBox_aer = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_aer.setGeometry(QtCore.QRect(413, 211, 347, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_aer.setFont(font)
        self.checkBox_aer.setObjectName("checkBox_aer")
        self.checkBox_adp = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_adp.setGeometry(QtCore.QRect(413, 248, 387, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_adp.setFont(font)
        self.checkBox_adp.setObjectName("checkBox_adp")
        self.checkBox_lvd = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_lvd.setGeometry(QtCore.QRect(413, 285, 400, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_lvd.setFont(font)
        self.checkBox_lvd.setObjectName("checkBox_lvd")
        self.checkBox_dru = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_dru.setGeometry(QtCore.QRect(413, 322, 179, 29))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_dru.setFont(font)
        self.checkBox_dru.setObjectName("checkBox_dru")
        self.checkBox_labfu = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_labfu.setGeometry(QtCore.QRect(413, 358, 428, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_labfu.setFont(font)
        self.checkBox_labfu.setObjectName("checkBox_labfu")
        self.checkBox_iop = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_iop.setGeometry(QtCore.QRect(413, 101, 222, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_iop.setFont(font)
        self.checkBox_iop.setObjectName("checkBox_iop")
        self.checkBox_idx = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_idx.setGeometry(QtCore.QRect(413, 64, 301, 30))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_idx.setFont(font)
        self.checkBox_idx.setObjectName("checkBox_idx")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/outline_file_upload_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(50, 20))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.openSaveDialog)



        self.label_show = QtWidgets.QLabel(self.centralwidget)
        self.label_show.setGeometry(QtCore.QRect(2, 0, 1, 20))
        font = QtGui.QFont()
        font.setFamily("TH SarabunPSK")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_show.setFont(font)
        self.label_show.setText("dddddd")
        self.label_show.setObjectName("label_show")
        # self.label_show.setGeometry(QtCore.QRect(2, 0, 1, 20))


        self.dateEdit_from = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_from.setGeometry(QtCore.QRect(260, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_from.setFont(font)
        self.dateEdit_from.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateEdit_from.setCalendarPopup(True)
        self.dateEdit_from.setCurrentSectionIndex(0)
        self.dateEdit_from.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_from.setObjectName("dateEdit_from")

        self.dateEdit_from.setDateTime(QtCore.QDateTime.currentDateTime())  # set date from crrent

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 30, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 39, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dateEdit_to = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_to.setGeometry(QtCore.QRect(440, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_to.setFont(font)
        self.dateEdit_to.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateEdit_to.setCalendarPopup(True)
        self.dateEdit_to.setObjectName("dateEdit_to")

        self.dateEdit_to.setDateTime(QtCore.QDateTime.currentDateTime())  # set date from crrent

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        # self.statusbar.showMessage("Please Enter Username & Password", 2000)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def openSaveDialog(self):
        widget = QWidget()
        dialog = QFileDialog()
        dir = dialog.getExistingDirectory(widget, 'Select directory')
    # def openSaveDialog(self):
        dateEdit_from = self.dateEdit_from.date()
        dateFrom = dateEdit_from.toPyDate()
        dateEdit_to = self.dateEdit_to.date()
        dateto = dateEdit_to.toPyDate()
        exportFile = DataBase()


        nameFile = []

        if self.checkBox_opd.isChecked():
            exportFile.export('OPD', dateFrom, dateto, dir)
            nameFile.append('OPD')

        if self.checkBox_pat.isChecked():
            exportFile.export('PAT', dateFrom, dateto, dir)
            nameFile.append('PAT')

        if self.checkBox_ins.isChecked():
            exportFile.export('INS', dateFrom, dateto, dir)
            nameFile.append('INS')

        msg = msgBox()
        msg.info("Export {} Success!! \n{} ".format(nameFile, dir))



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Export e-Claim v.1.0.0"))
        self.groupBox.setTitle(_translate("MainWindow", "16 File"))
        self.checkBox.setText(_translate("MainWindow", "Select All"))
        self.checkBox_pat.setText(_translate("MainWindow", "PAT แฟ้มข้อมูลผู้ป่วยกลาง "))
        self.checkBox_ins.setText(_translate("MainWindow", "INS แฟ้มข้อมูลผู้มีสิทธิการรักษาพยาบาล "))
        self.checkBox_oop.setText(_translate("MainWindow", "OOP แฟ้มข้อมูลหัตถการผู้ป่วยนอก "))
        self.checkBox_ipd.setText(_translate("MainWindow", "IPD แฟ้มข้อมูลผู้ป่วยใน "))
        self.checkBox_irf.setText(_translate("MainWindow", "IRF แฟ้มข้อมูลผู้ป่วยในที่ต้องส่งต่อ"))
        self.checkBox_opd.setText(_translate("MainWindow", "OPD แฟ้มข้อมูลการมารับบริการผู้ป่วยนอก"))
        self.checkBox_orf.setText(_translate("MainWindow", "ORF แฟ้มข้อมูลผู้ป่วยนอกที่ต้องส่งต่อ"))
        self.checkBox_odx.setText(_translate("MainWindow", "ODX แฟ้มข้อมูลวินิจฉัยโรคผู้ป่วยนอก "))
        self.checkBox_cht.setText(_translate("MainWindow", "CHT แฟ้มข้อมูลการเงิน (แบบสรุป)"))
        self.checkBox_cha.setText(_translate("MainWindow", "CHA แฟ้มข้อมูลการเงิน (แบบรายละเอียด) "))
        self.checkBox_aer.setText(_translate("MainWindow", "AER แฟ้มข้อมูลอุบัติเหตุ ฉุกเฉิน และรับส่งเพื่อรักษา "))
        self.checkBox_adp.setText(_translate("MainWindow", "ADP แฟ้มข้อมูลค่าใช้จ่ายเพิ่ม และบริการที่ยังไม่ได้จัดหมวด "))
        self.checkBox_lvd.setText(_translate("MainWindow", "LVD แฟ้มข้อมูลกรณีที่ผู้ป่วยมีการลากลับบ้าน (Leave day) "))
        self.checkBox_dru.setText(_translate("MainWindow", "DRU แฟ้มข้อมูลการใช้ยา"))
        self.checkBox_labfu.setText(_translate("MainWindow", "LABFU แฟ้มข้อมูลการตรวจทางห้องปฏิบัติการของผู้ป่วยโรคเรื้อรัง"))
        self.checkBox_iop.setText(_translate("MainWindow", "IOP แฟ้มข้อมูลหัตถการผู้ป่วยใน"))
        self.checkBox_idx.setText(_translate("MainWindow", "IDX มาตรฐานแฟ้มข้อมูลวินิจฉัยโรคผู้ป่วยใน"))
        self.pushButton.setText(_translate("MainWindow", "Export"))
        self.dateEdit_from.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.label.setText(_translate("MainWindow", "From"))
        self.dateEdit_to.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_export()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

